2019-10-28 14:54:21,670 ERROR: Exception on /search [GET] [in /Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/app/main/routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/app/search.py", line 26, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 805, in search
    "GET", _make_path(index, "_search"), params=params, body=body
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index', post, index_or_alias)
2019-10-28 14:59:50,208 INFO: Microblog startup [in /Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/app/__init__.py:77]
2019-10-28 14:59:51,059 ERROR: Exception on /search [GET] [in /Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/app/main/routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/app/search.py", line 26, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 805, in search
    "GET", _make_path(index, "_search"), params=params, body=body
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index', post, index_or_alias)
2019-10-28 15:00:12,704 ERROR: Exception on /search [GET] [in /Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/app/main/routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/kishored/coding/python-coding/flask-trailers/py-flask-mega/microblog/app/search.py", line 28, in query_index
    return ids, search['hits']['total']['value']
TypeError: 'int' object is not subscriptable
